server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://api:3000/api/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /agent/ {
    proxy_pass http://collector-agent:3100/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /agent-compliance/ {
    proxy_pass http://compliance-agent:3101/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
