PRAGMA foreign_keys = OFF;

DROP VIEW IF EXISTS vw_pagos_clientes; DROP VIEW IF EXISTS vw_historial_pedidos; DROP VIEW IF EXISTS vw_pedidos_actuales;
DROP TRIGGER IF EXISTS t_paz_y_salvo;
DROP INDEX IF EXISTS ux_pedido_codigo_pedido;

DROP TABLE IF EXISTS REPORTE_MENSUAL; DROP TABLE IF EXISTS HISTORIAL_PEDIDO; DROP TABLE IF EXISTS ETIQUETA;
DROP TABLE IF EXISTS PAGO; DROP TABLE IF EXISTS DETALLE_PEDIDO; DROP TABLE IF EXISTS PEDIDO;
DROP TABLE IF EXISTS INVENTARIO; DROP TABLE IF EXISTS PRODUCTO; DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS PLAN_PEDIDO; DROP TABLE IF EXISTS TARJETA; DROP TABLE IF EXISTS CLIENTE; DROP TABLE IF EXISTS PROVINCIA;

PRAGMA foreign_keys = ON;
